version: '3.8'

services:
  db:
    ports:
      - "5433:5432"

  minio:
    ports:
      - "9000:9000"
      - "9090:9090"

  app:
    profiles: ["do-not-start"]

networks:
  data_mgmt_net:
    name: data_mgmt_net
