version: '3.8'

services:
  app-dev:
    build:
      context: ..
      dockerfile: Dockerfile
      target: base
    volumes:
      - ..:/app:delegate
      - node_modules_volume:/app/frontend/node_modules
      - npm_cache:/root/.npm
    command: sleep infinity
    networks:
      - data_mgmt_net
    env_file:
      - ../.env

networks:
  data_mgmt_net:
    external: true
    name: data_mgmt_net
