apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-project-manager
spec:
  selector:
    matchLabels:
      app: image-project-manager
  template:
    metadata:
      labels:
        app: image-project-manager
    spec:
      containers:
      - name: app
        image: image-project-manager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: image-project-manager
spec:
  type: NodePort
  selector:
    app: image-project-manager
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080